<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_W13S03_Katalon Studio Assignment</name>
   <tag></tag>
   <elementGuidId>f8cd47b7-6e62-4c0a-9a44-257a670b2ee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='module-46875']/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#module-46875 > div > div.mod-indent-outer.w-100 > div:nth-of-type(2) > div.activityinstance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^W13S03_Katalon Studio Assignment$/ >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99fddde5-31eb-42c9-8cd2-74da1a94a548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activityinstance</value>
      <webElementGuid>4aad689d-a1a3-4b7e-98fc-89d6ff58a564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>W13S03_Katalon Studio Assignment</value>
      <webElementGuid>06bb875b-91b4-4cab-81c3-77f8f19fcf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-46875&quot;)/div[1]/div[@class=&quot;mod-indent-outer w-100&quot;]/div[2]/div[@class=&quot;activityinstance&quot;]</value>
      <webElementGuid>c5d6b1e1-9bb9-458b-9970-722faf322d17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='module-46875']/div/div/div[2]/div</value>
      <webElementGuid>119ddd72-e6a4-46ac-bbdc-f3dbb3bd8e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[12]/following::div[5]</value>
      <webElementGuid>43cb5217-7a75-4a55-9427-db581e39fb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/div</value>
      <webElementGuid>fab95798-0334-4497-9dac-cc9d482a49a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'W13S03_Katalon Studio Assignment' or . = 'W13S03_Katalon Studio Assignment')]</value>
      <webElementGuid>f167cfe0-7f22-4e14-ad10-2f17ecf7130c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
